# -*- coding: utf-8 -*-
"""
patterns_data.py — content for the "72 Japanese Sentence Patterns" page.

Each pattern is a dict:
  num     : 1..72 (in order)
  jp      : the pattern headword (with ～/… placeholders; furigana via <ruby>)
  romaji  : romaji of the headword
  name    : short English label
  formula : the "Pattern" box contents
  note    : 1-2 sentence plain-English explanation
  examples: list of 2-3 everyday sentences, each:
      jp     : Japanese with <ruby>kanji<rt>reading</rt></ruby> furigana
      romaji : romaji
      en     : natural English
      zh     : Simplified Chinese
      pinyin : toned pinyin
      bd     : [(word, gloss), ...] word-by-word breakdown

Rendered to patterns.html by build_patterns.py.
"""

PATTERNS = [
    {
        "num": 1,
        "jp": "これは〜です",
        "romaji": "Kore wa ~ desu",
        "name": "This is ~",
        "formula": "これは + [noun] + です",
        "note": "Point at something near you and name it. これ = “this (thing by me),” は marks the topic, and です is the polite “is/am/are.”",
        "examples": [
            {
                "jp": "これは<ruby>本<rt>ほん</rt></ruby>です。",
                "romaji": "Kore wa hon desu.",
                "en": "This is a book.",
                "zh": "这是书。",
                "pinyin": "Zhè shì shū.",
                "bd": [("これ", "this"), ("は", "topic"), ("本", "book"), ("です", "is (polite)")],
            },
            {
                "jp": "これは<ruby>私<rt>わたし</rt></ruby>のかばんです。",
                "romaji": "Kore wa watashi no kaban desu.",
                "en": "This is my bag.",
                "zh": "这是我的包。",
                "pinyin": "Zhè shì wǒ de bāo.",
                "bd": [("これ", "this"), ("は", "topic"), ("私", "I"), ("の", "'s"), ("かばん", "bag"), ("です", "is")],
            },
        ],
    },
    {
        "num": 2,
        "jp": "<ruby>私<rt>わたし</rt></ruby>は〜です",
        "romaji": "Watashi wa ~ desu",
        "name": "I am ~",
        "formula": "私は + [noun] + です",
        "note": "Introduce yourself or state your role. 私 = “I,” and は marks you as the topic of the sentence.",
        "examples": [
            {
                "jp": "<ruby>私<rt>わたし</rt></ruby>は<ruby>学生<rt>がくせい</rt></ruby>です。",
                "romaji": "Watashi wa gakusei desu.",
                "en": "I'm a student.",
                "zh": "我是学生。",
                "pinyin": "Wǒ shì xuésheng.",
                "bd": [("私", "I"), ("は", "topic"), ("学生", "student"), ("です", "am")],
            },
            {
                "jp": "<ruby>私<rt>わたし</rt></ruby>はケビンです。",
                "romaji": "Watashi wa Kebin desu.",
                "en": "I'm Kevin.",
                "zh": "我是凯文。",
                "pinyin": "Wǒ shì Kǎiwén.",
                "bd": [("私", "I"), ("は", "topic"), ("ケビン", "Kevin"), ("です", "am")],
            },
        ],
    },
    {
        "num": 3,
        "jp": "〜は…です（1）",
        "romaji": "~ wa ... desu",
        "name": "~ is … (identity)",
        "formula": "[topic] は + [noun] + です",
        "note": "State what someone or something is. The topic (marked by は) is identified by the noun before です.",
        "examples": [
            {
                "jp": "<ruby>田中<rt>たなか</rt></ruby>さんは<ruby>先生<rt>せんせい</rt></ruby>です。",
                "romaji": "Tanaka-san wa sensei desu.",
                "en": "Mr. Tanaka is a teacher.",
                "zh": "田中是老师。",
                "pinyin": "Tiánzhōng shì lǎoshī.",
                "bd": [("田中さん", "Mr. Tanaka"), ("は", "topic"), ("先生", "teacher"), ("です", "is")],
            },
            {
                "jp": "あの<ruby>人<rt>ひと</rt></ruby>は<ruby>医者<rt>いしゃ</rt></ruby>です。",
                "romaji": "Ano hito wa isha desu.",
                "en": "That person is a doctor.",
                "zh": "那个人是医生。",
                "pinyin": "Nàge rén shì yīshēng.",
                "bd": [("あの", "that"), ("人", "person"), ("は", "topic"), ("医者", "doctor"), ("です", "is")],
            },
        ],
    },
    {
        "num": 4,
        "jp": "〜は…です（2）",
        "romaji": "~ wa ... desu",
        "name": "~ is … (description)",
        "formula": "[topic] は + [adjective] + です",
        "note": "Describe the topic with an adjective. です keeps the adjective polite and works with both い- and な-adjectives.",
        "examples": [
            {
                "jp": "この<ruby>店<rt>みせ</rt></ruby>は<ruby>有名<rt>ゆうめい</rt></ruby>です。",
                "romaji": "Kono mise wa yuumei desu.",
                "en": "This shop is famous.",
                "zh": "这家店很有名。",
                "pinyin": "Zhè jiā diàn hěn yǒumíng.",
                "bd": [("この", "this"), ("店", "shop"), ("は", "topic"), ("有名", "famous"), ("です", "is")],
            },
            {
                "jp": "<ruby>今日<rt>きょう</rt></ruby>は<ruby>暑<rt>あつ</rt></ruby>いです。",
                "romaji": "Kyou wa atsui desu.",
                "en": "It's hot today.",
                "zh": "今天很热。",
                "pinyin": "Jīntiān hěn rè.",
                "bd": [("今日", "today"), ("は", "topic"), ("暑い", "hot"), ("です", "is")],
            },
        ],
    },
    {
        "num": 5,
        "jp": "〜は…にいます",
        "romaji": "~ wa ... ni imasu",
        "name": "~ is (located) at … (animate)",
        "formula": "[living thing] は + [place] + に + います",
        "note": "Say where a living thing is. います is the “to be / exist” verb for people and animals; に marks the location.",
        "examples": [
            {
                "jp": "<ruby>猫<rt>ねこ</rt></ruby>は<ruby>部屋<rt>へや</rt></ruby>にいます。",
                "romaji": "Neko wa heya ni imasu.",
                "en": "The cat is in the room.",
                "zh": "猫在房间里。",
                "pinyin": "Māo zài fángjiān lǐ.",
                "bd": [("猫", "cat"), ("は", "topic"), ("部屋", "room"), ("に", "in"), ("います", "is (animate)")],
            },
            {
                "jp": "<ruby>父<rt>ちち</rt></ruby>は<ruby>会社<rt>かいしゃ</rt></ruby>にいます。",
                "romaji": "Chichi wa kaisha ni imasu.",
                "en": "My father is at the office.",
                "zh": "爸爸在公司。",
                "pinyin": "Bàba zài gōngsī.",
                "bd": [("父", "(my) father"), ("は", "topic"), ("会社", "company/office"), ("に", "at"), ("います", "is")],
            },
        ],
    },
    {
        "num": 6,
        "jp": "〜は…にあります",
        "romaji": "~ wa ... ni arimasu",
        "name": "~ is (located) at … (inanimate)",
        "formula": "[object/place] は + [place] + に + あります",
        "note": "Say where an object or place is. あります is the “to be / exist” verb for non-living things.",
        "examples": [
            {
                "jp": "<ruby>銀行<rt>ぎんこう</rt></ruby>は<ruby>駅<rt>えき</rt></ruby>の<ruby>前<rt>まえ</rt></ruby>にあります。",
                "romaji": "Ginkou wa eki no mae ni arimasu.",
                "en": "The bank is in front of the station.",
                "zh": "银行在车站前面。",
                "pinyin": "Yínháng zài chēzhàn qiánmiàn.",
                "bd": [("銀行", "bank"), ("は", "topic"), ("駅", "station"), ("の", "'s"), ("前", "front"), ("に", "at"), ("あります", "is (inanimate)")],
            },
            {
                "jp": "トイレはあそこにあります。",
                "romaji": "Toire wa asoko ni arimasu.",
                "en": "The toilet is over there.",
                "zh": "厕所在那边。",
                "pinyin": "Cèsuǒ zài nàbiān.",
                "bd": [("トイレ", "toilet"), ("は", "topic"), ("あそこ", "over there"), ("に", "at"), ("あります", "is")],
            },
        ],
    },
    {
        "num": 7,
        "jp": "〜します",
        "romaji": "~ shimasu",
        "name": "do ~ / will do ~",
        "formula": "[object] を + [verb]-ます",
        "note": "The basic polite verb ending for present or future actions. を marks the thing the action acts on.",
        "examples": [
            {
                "jp": "<ruby>毎日<rt>まいにち</rt></ruby><ruby>日本語<rt>にほんご</rt></ruby>を<ruby>勉強<rt>べんきょう</rt></ruby>します。",
                "romaji": "Mainichi nihongo o benkyou shimasu.",
                "en": "I study Japanese every day.",
                "zh": "我每天学习日语。",
                "pinyin": "Wǒ měitiān xuéxí Rìyǔ.",
                "bd": [("毎日", "every day"), ("日本語", "Japanese"), ("を", "[object]"), ("勉強します", "study")],
            },
            {
                "jp": "<ruby>明日<rt>あした</rt></ruby>テニスをします。",
                "romaji": "Ashita tenisu o shimasu.",
                "en": "I'll play tennis tomorrow.",
                "zh": "我明天打网球。",
                "pinyin": "Wǒ míngtiān dǎ wǎngqiú.",
                "bd": [("明日", "tomorrow"), ("テニス", "tennis"), ("を", "[object]"), ("します", "do/play")],
            },
        ],
    },
    {
        "num": 8,
        "jp": "〜したいです",
        "romaji": "~ shitai desu",
        "name": "want to do ~",
        "formula": "[verb stem] + たいです",
        "note": "Express your own desire to do something. Attach たい to the verb stem; the object often takes が instead of を.",
        "examples": [
            {
                "jp": "<ruby>寿司<rt>すし</rt></ruby>が<ruby>食<rt>た</rt></ruby>べたいです。",
                "romaji": "Sushi ga tabetai desu.",
                "en": "I want to eat sushi.",
                "zh": "我想吃寿司。",
                "pinyin": "Wǒ xiǎng chī shòusī.",
                "bd": [("寿司", "sushi"), ("が", "[object]"), ("食べたい", "want to eat"), ("です", "(polite)")],
            },
            {
                "jp": "<ruby>日本<rt>にほん</rt></ruby>に<ruby>行<rt>い</rt></ruby>きたいです。",
                "romaji": "Nihon ni ikitai desu.",
                "en": "I want to go to Japan.",
                "zh": "我想去日本。",
                "pinyin": "Wǒ xiǎng qù Rìběn.",
                "bd": [("日本", "Japan"), ("に", "to"), ("行きたい", "want to go"), ("です", "(polite)")],
            },
        ],
    },
    {
        "num": 9,
        "jp": "〜しています（1）",
        "romaji": "~ shite imasu",
        "name": "be doing ~ (in progress)",
        "formula": "[verb] て-form + います",
        "note": "Describe an action happening right now. Take the て-form of the verb and add います.",
        "examples": [
            {
                "jp": "<ruby>今<rt>いま</rt></ruby>、<ruby>本<rt>ほん</rt></ruby>を<ruby>読<rt>よ</rt></ruby>んでいます。",
                "romaji": "Ima, hon o yonde imasu.",
                "en": "I'm reading a book right now.",
                "zh": "我现在在看书。",
                "pinyin": "Wǒ xiànzài zài kàn shū.",
                "bd": [("今", "now"), ("本", "book"), ("を", "[object]"), ("読んでいます", "am reading")],
            },
            {
                "jp": "<ruby>母<rt>はは</rt></ruby>は<ruby>料理<rt>りょうり</rt></ruby>をしています。",
                "romaji": "Haha wa ryouri o shite imasu.",
                "en": "My mother is cooking.",
                "zh": "妈妈在做饭。",
                "pinyin": "Māma zài zuò fàn.",
                "bd": [("母", "(my) mother"), ("は", "topic"), ("料理", "cooking"), ("を", "[object]"), ("しています", "is doing")],
            },
        ],
    },
    {
        "num": 10,
        "jp": "〜しています（2）",
        "romaji": "~ shite imasu",
        "name": "~ (ongoing state / habit)",
        "formula": "[verb] て-form + います",
        "note": "The same て+います also expresses a continuing state or habit — not just a live action, but how things stand.",
        "examples": [
            {
                "jp": "<ruby>銀行<rt>ぎんこう</rt></ruby>に<ruby>勤<rt>つと</rt></ruby>めています。",
                "romaji": "Ginkou ni tsutomete imasu.",
                "en": "I work at a bank.",
                "zh": "我在银行工作。",
                "pinyin": "Wǒ zài yínháng gōngzuò.",
                "bd": [("銀行", "bank"), ("に", "at"), ("勤めています", "am employed")],
            },
            {
                "jp": "<ruby>結婚<rt>けっこん</rt></ruby>しています。",
                "romaji": "Kekkon shite imasu.",
                "en": "I'm married.",
                "zh": "我已经结婚了。",
                "pinyin": "Wǒ yǐjīng jiéhūn le.",
                "bd": [("結婚しています", "am married")],
            },
        ],
    },
    {
        "num": 11,
        "jp": "〜しました",
        "romaji": "~ shimashita",
        "name": "did ~ (past)",
        "formula": "[verb stem] + ました",
        "note": "The polite past tense. Use it for actions that are already finished.",
        "examples": [
            {
                "jp": "<ruby>昨日<rt>きのう</rt></ruby><ruby>映画<rt>えいが</rt></ruby>を<ruby>見<rt>み</rt></ruby>ました。",
                "romaji": "Kinou eiga o mimashita.",
                "en": "I watched a movie yesterday.",
                "zh": "我昨天看了电影。",
                "pinyin": "Wǒ zuótiān kàn le diànyǐng.",
                "bd": [("昨日", "yesterday"), ("映画", "movie"), ("を", "[object]"), ("見ました", "watched")],
            },
            {
                "jp": "<ruby>朝<rt>あさ</rt></ruby>ごはんを<ruby>食<rt>た</rt></ruby>べました。",
                "romaji": "Asagohan o tabemashita.",
                "en": "I ate breakfast.",
                "zh": "我吃了早饭。",
                "pinyin": "Wǒ chī le zǎofàn.",
                "bd": [("朝ごはん", "breakfast"), ("を", "[object]"), ("食べました", "ate")],
            },
        ],
    },
    {
        "num": 12,
        "jp": "もう〜しました",
        "romaji": "mou ~ shimashita",
        "name": "already did ~",
        "formula": "もう + [verb stem] + ました",
        "note": "Say something is already done. もう = “already,” added in front of the past-tense verb.",
        "examples": [
            {
                "jp": "もう<ruby>宿題<rt>しゅくだい</rt></ruby>をしました。",
                "romaji": "Mou shukudai o shimashita.",
                "en": "I've already done my homework.",
                "zh": "我已经做完作业了。",
                "pinyin": "Wǒ yǐjīng zuòwán zuòyè le.",
                "bd": [("もう", "already"), ("宿題", "homework"), ("を", "[object]"), ("しました", "did")],
            },
            {
                "jp": "もう<ruby>昼<rt>ひる</rt></ruby>ごはんを<ruby>食<rt>た</rt></ruby>べました。",
                "romaji": "Mou hirugohan o tabemashita.",
                "en": "I've already had lunch.",
                "zh": "我已经吃过午饭了。",
                "pinyin": "Wǒ yǐjīng chīguò wǔfàn le.",
                "bd": [("もう", "already"), ("昼ごはん", "lunch"), ("を", "[object]"), ("食べました", "ate")],
            },
        ],
    },
    {
        "num": 13,
        "jp": "〜したことがあります",
        "romaji": "~ shita koto ga arimasu",
        "name": "have done ~ before",
        "formula": "[verb] past-plain + ことがあります",
        "note": "Talk about an experience — something you have done at least once. Use the plain past verb + ことがあります.",
        "examples": [
            {
                "jp": "<ruby>日本<rt>にほん</rt></ruby>に<ruby>行<rt>い</rt></ruby>ったことがあります。",
                "romaji": "Nihon ni itta koto ga arimasu.",
                "en": "I have been to Japan.",
                "zh": "我去过日本。",
                "pinyin": "Wǒ qùguò Rìběn.",
                "bd": [("日本", "Japan"), ("に", "to"), ("行った", "went"), ("こと", "the fact/act"), ("が", "[subject]"), ("あります", "there is (= have)")],
            },
            {
                "jp": "<ruby>馬<rt>うま</rt></ruby>に<ruby>乗<rt>の</rt></ruby>ったことがあります。",
                "romaji": "Uma ni notta koto ga arimasu.",
                "en": "I have ridden a horse before.",
                "zh": "我骑过马。",
                "pinyin": "Wǒ qíguò mǎ.",
                "bd": [("馬", "horse"), ("に", "on"), ("乗った", "rode"), ("こと", "the fact/act"), ("が", "[subject]"), ("あります", "have")],
            },
        ],
    },
    {
        "num": 14,
        "jp": "〜（することが）できます",
        "romaji": "~ (suru koto ga) dekimasu",
        "name": "can do ~ / be able to",
        "formula": "[noun] が + できます  /  [verb] こと + が + できます",
        "note": "Express ability. Use [noun] + ができます, or take a dictionary-form verb + ことができます.",
        "examples": [
            {
                "jp": "<ruby>日本語<rt>にほんご</rt></ruby>を<ruby>話<rt>はな</rt></ruby>すことができます。",
                "romaji": "Nihongo o hanasu koto ga dekimasu.",
                "en": "I can speak Japanese.",
                "zh": "我会说日语。",
                "pinyin": "Wǒ huì shuō Rìyǔ.",
                "bd": [("日本語", "Japanese"), ("を", "[object]"), ("話す", "speak"), ("こと", "the act"), ("が", "[subject]"), ("できます", "can do")],
            },
            {
                "jp": "ピアノができます。",
                "romaji": "Piano ga dekimasu.",
                "en": "I can play the piano.",
                "zh": "我会弹钢琴。",
                "pinyin": "Wǒ huì tán gāngqín.",
                "bd": [("ピアノ", "piano"), ("が", "[subject]"), ("できます", "can do")],
            },
        ],
    },
    {
        "num": 15,
        "jp": "〜してもいいです",
        "romaji": "~ shitemo ii desu",
        "name": "may do ~ / it's OK to ~",
        "formula": "[verb] て-form + もいいです",
        "note": "Give or ask permission. て-form + もいいです literally means “even if you do ~, it's fine.” Add か to ask.",
        "examples": [
            {
                "jp": "ここで<ruby>写真<rt>しゃしん</rt></ruby>を<ruby>撮<rt>と</rt></ruby>ってもいいです。",
                "romaji": "Koko de shashin o totte mo ii desu.",
                "en": "You may take photos here.",
                "zh": "这里可以拍照。",
                "pinyin": "Zhèlǐ kěyǐ pāizhào.",
                "bd": [("ここ", "here"), ("で", "at"), ("写真", "photo"), ("を", "[object]"), ("撮っても", "even if (you) take"), ("いい", "good"), ("です", "is")],
            },
            {
                "jp": "<ruby>入<rt>はい</rt></ruby>ってもいいですか。",
                "romaji": "Haitte mo ii desu ka.",
                "en": "May I come in?",
                "zh": "我可以进来吗？",
                "pinyin": "Wǒ kěyǐ jìnlái ma?",
                "bd": [("入っても", "even if (I) enter"), ("いい", "good"), ("です", "is"), ("か", "?")],
            },
        ],
    },
    {
        "num": 16,
        "jp": "〜は<ruby>何<rt>なん</rt></ruby>ですか",
        "romaji": "~ wa nan desu ka",
        "name": "what is ~?",
        "formula": "[topic] は + 何 + ですか",
        "note": "Ask what something is. 何 = “what,” and か turns the sentence into a question.",
        "examples": [
            {
                "jp": "これは<ruby>何<rt>なん</rt></ruby>ですか。",
                "romaji": "Kore wa nan desu ka.",
                "en": "What is this?",
                "zh": "这是什么？",
                "pinyin": "Zhè shì shénme?",
                "bd": [("これ", "this"), ("は", "topic"), ("何", "what"), ("です", "is"), ("か", "?")],
            },
            {
                "jp": "あなたの<ruby>趣味<rt>しゅみ</rt></ruby>は<ruby>何<rt>なん</rt></ruby>ですか。",
                "romaji": "Anata no shumi wa nan desu ka.",
                "en": "What is your hobby?",
                "zh": "你的爱好是什么？",
                "pinyin": "Nǐ de àihào shì shénme?",
                "bd": [("あなた", "you"), ("の", "'s"), ("趣味", "hobby"), ("は", "topic"), ("何", "what"), ("です", "is"), ("か", "?")],
            },
        ],
    },
    {
        "num": 17,
        "jp": "〜は<ruby>誰<rt>だれ</rt></ruby>ですか",
        "romaji": "~ wa dare desu ka",
        "name": "who is ~?",
        "formula": "[topic] は + 誰 + ですか",
        "note": "Ask who someone is. 誰 = “who.”",
        "examples": [
            {
                "jp": "あの<ruby>人<rt>ひと</rt></ruby>は<ruby>誰<rt>だれ</rt></ruby>ですか。",
                "romaji": "Ano hito wa dare desu ka.",
                "en": "Who is that person?",
                "zh": "那个人是谁？",
                "pinyin": "Nàge rén shì shéi?",
                "bd": [("あの", "that"), ("人", "person"), ("は", "topic"), ("誰", "who"), ("です", "is"), ("か", "?")],
            },
            {
                "jp": "この<ruby>人<rt>ひと</rt></ruby>は<ruby>誰<rt>だれ</rt></ruby>ですか。",
                "romaji": "Kono hito wa dare desu ka.",
                "en": "Who is this person?",
                "zh": "这个人是谁？",
                "pinyin": "Zhège rén shì shéi?",
                "bd": [("この", "this"), ("人", "person"), ("は", "topic"), ("誰", "who"), ("です", "is"), ("か", "?")],
            },
        ],
    },
    {
        "num": 18,
        "jp": "〜はいつですか",
        "romaji": "~ wa itsu desu ka",
        "name": "when is ~?",
        "formula": "[topic] は + いつ + ですか",
        "note": "Ask when something happens. いつ = “when.”",
        "examples": [
            {
                "jp": "<ruby>試験<rt>しけん</rt></ruby>はいつですか。",
                "romaji": "Shiken wa itsu desu ka.",
                "en": "When is the exam?",
                "zh": "考试是什么时候？",
                "pinyin": "Kǎoshì shì shénme shíhou?",
                "bd": [("試験", "exam"), ("は", "topic"), ("いつ", "when"), ("です", "is"), ("か", "?")],
            },
            {
                "jp": "<ruby>誕生日<rt>たんじょうび</rt></ruby>はいつですか。",
                "romaji": "Tanjoubi wa itsu desu ka.",
                "en": "When is your birthday?",
                "zh": "你的生日是什么时候？",
                "pinyin": "Nǐ de shēngrì shì shénme shíhou?",
                "bd": [("誕生日", "birthday"), ("は", "topic"), ("いつ", "when"), ("です", "is"), ("か", "?")],
            },
        ],
    },
    {
        "num": 19,
        "jp": "〜はどこですか",
        "romaji": "~ wa doko desu ka",
        "name": "where is ~?",
        "formula": "[topic] は + どこ + ですか",
        "note": "Ask where something is. どこ = “where.”",
        "examples": [
            {
                "jp": "<ruby>駅<rt>えき</rt></ruby>はどこですか。",
                "romaji": "Eki wa doko desu ka.",
                "en": "Where is the station?",
                "zh": "车站在哪里？",
                "pinyin": "Chēzhàn zài nǎlǐ?",
                "bd": [("駅", "station"), ("は", "topic"), ("どこ", "where"), ("です", "is"), ("か", "?")],
            },
            {
                "jp": "お<ruby>手洗<rt>てあら</rt></ruby>いはどこですか。",
                "romaji": "Otearai wa doko desu ka.",
                "en": "Where is the restroom?",
                "zh": "洗手间在哪里？",
                "pinyin": "Xǐshǒujiān zài nǎlǐ?",
                "bd": [("お手洗い", "restroom"), ("は", "topic"), ("どこ", "where"), ("です", "is"), ("か", "?")],
            },
        ],
    },
    {
        "num": 20,
        "jp": "どうして〜? なぜ〜?",
        "romaji": "Doushite ~ / Naze ~",
        "name": "why ~?",
        "formula": "どうして / なぜ + [clause] + か",
        "note": "Ask for a reason. どうして and なぜ both mean “why” (どうして is more conversational). んですか softens it to “how come.”",
        "examples": [
            {
                "jp": "どうして<ruby>遅<rt>おく</rt></ruby>れたんですか。",
                "romaji": "Doushite okureta n desu ka.",
                "en": "Why were you late?",
                "zh": "你为什么迟到了？",
                "pinyin": "Nǐ wèishénme chídào le?",
                "bd": [("どうして", "why"), ("遅れた", "were late"), ("んです", "(explanatory)"), ("か", "?")],
            },
            {
                "jp": "なぜ<ruby>日本語<rt>にほんご</rt></ruby>を<ruby>勉強<rt>べんきょう</rt></ruby>しているんですか。",
                "romaji": "Naze nihongo o benkyou shite iru n desu ka.",
                "en": "Why are you studying Japanese?",
                "zh": "你为什么在学日语？",
                "pinyin": "Nǐ wèishénme zài xué Rìyǔ?",
                "bd": [("なぜ", "why"), ("日本語", "Japanese"), ("を", "[object]"), ("勉強している", "are studying"), ("んです", "(explanatory)"), ("か", "?")],
            },
        ],
    },
    {
        "num": 21,
        "jp": "〜はどうですか",
        "romaji": "~ wa dou desu ka",
        "name": "how is ~? / how about ~?",
        "formula": "[topic] は + どう + ですか",
        "note": "Ask for an opinion, or make a friendly suggestion. どう = “how / how about.”",
        "examples": [
            {
                "jp": "<ruby>新<rt>あたら</rt></ruby>しい<ruby>仕事<rt>しごと</rt></ruby>はどうですか。",
                "romaji": "Atarashii shigoto wa dou desu ka.",
                "en": "How is the new job?",
                "zh": "新工作怎么样？",
                "pinyin": "Xīn gōngzuò zěnmeyàng?",
                "bd": [("新しい", "new"), ("仕事", "job"), ("は", "topic"), ("どう", "how"), ("です", "is"), ("か", "?")],
            },
            {
                "jp": "コーヒーはどうですか。",
                "romaji": "Koohii wa dou desu ka.",
                "en": "How about some coffee?",
                "zh": "来杯咖啡怎么样？",
                "pinyin": "Lái bēi kāfēi zěnmeyàng?",
                "bd": [("コーヒー", "coffee"), ("は", "topic"), ("どう", "how about"), ("です", "is"), ("か", "?")],
            },
        ],
    },
    {
        "num": 22,
        "jp": "〜おめでとう",
        "romaji": "~ omedetou",
        "name": "congratulations on ~",
        "formula": "[occasion] + おめでとう（ございます）",
        "note": "Offer congratulations. Add ございます to make it polite.",
        "examples": [
            {
                "jp": "<ruby>誕生日<rt>たんじょうび</rt></ruby>おめでとう。",
                "romaji": "Tanjoubi omedetou.",
                "en": "Happy birthday!",
                "zh": "生日快乐！",
                "pinyin": "Shēngrì kuàilè!",
                "bd": [("誕生日", "birthday"), ("おめでとう", "congratulations")],
            },
            {
                "jp": "<ruby>合格<rt>ごうかく</rt></ruby>おめでとうございます。",
                "romaji": "Goukaku omedetou gozaimasu.",
                "en": "Congratulations on passing!",
                "zh": "恭喜你考上了！",
                "pinyin": "Gōngxǐ nǐ kǎoshàng le!",
                "bd": [("合格", "passing (an exam)"), ("おめでとうございます", "congratulations (polite)")],
            },
        ],
    },
    {
        "num": 23,
        "jp": "〜ありがとう",
        "romaji": "~ arigatou",
        "name": "thank you for ~",
        "formula": "[thing] + ありがとう（ございます）",
        "note": "Express thanks for a thing. Add ございます (or ございました for past kindness) to be polite.",
        "examples": [
            {
                "jp": "プレゼントありがとう。",
                "romaji": "Purezento arigatou.",
                "en": "Thanks for the present.",
                "zh": "谢谢你的礼物。",
                "pinyin": "Xièxie nǐ de lǐwù.",
                "bd": [("プレゼント", "present"), ("ありがとう", "thank you")],
            },
            {
                "jp": "<ruby>今日<rt>きょう</rt></ruby>はありがとうございました。",
                "romaji": "Kyou wa arigatou gozaimashita.",
                "en": "Thank you for today.",
                "zh": "今天谢谢你了。",
                "pinyin": "Jīntiān xièxie nǐ le.",
                "bd": [("今日", "today"), ("は", "topic"), ("ありがとうございました", "thank you (past, polite)")],
            },
        ],
    },
    {
        "num": 24,
        "jp": "〜してくれてありがとう",
        "romaji": "~ shitekurete arigatou",
        "name": "thank you for doing ~",
        "formula": "[verb] て-form + くれて + ありがとう",
        "note": "Thank someone for an action they did for you. くれて marks that the action was a favor toward you.",
        "examples": [
            {
                "jp": "<ruby>来<rt>き</rt></ruby>てくれてありがとう。",
                "romaji": "Kite kurete arigatou.",
                "en": "Thanks for coming.",
                "zh": "谢谢你来。",
                "pinyin": "Xièxie nǐ lái.",
                "bd": [("来て", "come"), ("くれて", "(did for me)"), ("ありがとう", "thank you")],
            },
            {
                "jp": "<ruby>手伝<rt>てつだ</rt></ruby>ってくれてありがとう。",
                "romaji": "Tetsudatte kurete arigatou.",
                "en": "Thanks for helping me.",
                "zh": "谢谢你帮我。",
                "pinyin": "Xièxie nǐ bāng wǒ.",
                "bd": [("手伝って", "help"), ("くれて", "(did for me)"), ("ありがとう", "thank you")],
            },
        ],
    },
    {
        "num": 25,
        "jp": "〜（して）ごめんなさい",
        "romaji": "~ (shite) gomennasai",
        "name": "sorry for ~",
        "formula": "[verb] て-form + ごめんなさい",
        "note": "Apologize. Use the て-form to say what you're sorry for, or just ごめんなさい on its own.",
        "examples": [
            {
                "jp": "<ruby>遅<rt>おく</rt></ruby>れてごめんなさい。",
                "romaji": "Okurete gomennasai.",
                "en": "Sorry for being late.",
                "zh": "对不起，我迟到了。",
                "pinyin": "Duìbuqǐ, wǒ chídào le.",
                "bd": [("遅れて", "being late"), ("ごめんなさい", "sorry")],
            },
            {
                "jp": "<ruby>待<rt>ま</rt></ruby>たせてごめんなさい。",
                "romaji": "Matasete gomennasai.",
                "en": "Sorry for keeping you waiting.",
                "zh": "对不起，让你久等了。",
                "pinyin": "Duìbuqǐ, ràng nǐ jiǔ děng le.",
                "bd": [("待たせて", "making (you) wait"), ("ごめんなさい", "sorry")],
            },
        ],
    },
    {
        "num": 26,
        "jp": "〜しませんか",
        "romaji": "~ shimasen ka",
        "name": "won't you ~? (invitation)",
        "formula": "[verb] polite-negative + か",
        "note": "Invite someone to do something with you. The polite negative + か sounds warm and inviting, not literally negative.",
        "examples": [
            {
                "jp": "<ruby>一緒<rt>いっしょ</rt></ruby>に<ruby>食事<rt>しょくじ</rt></ruby>しませんか。",
                "romaji": "Issho ni shokuji shimasen ka.",
                "en": "Would you like to have a meal together?",
                "zh": "要不要一起吃饭？",
                "pinyin": "Yào bu yào yìqǐ chīfàn?",
                "bd": [("一緒に", "together"), ("食事", "meal"), ("しませんか", "won't you do?")],
            },
            {
                "jp": "<ruby>映画<rt>えいが</rt></ruby>を<ruby>見<rt>み</rt></ruby>ませんか。",
                "romaji": "Eiga o mimasen ka.",
                "en": "Would you like to see a movie?",
                "zh": "要不要看电影？",
                "pinyin": "Yào bu yào kàn diànyǐng?",
                "bd": [("映画", "movie"), ("を", "[object]"), ("見ませんか", "won't you watch?")],
            },
        ],
    },
    {
        "num": 27,
        "jp": "〜しましょうか",
        "romaji": "~ shimashou ka",
        "name": "shall I / shall we ~?",
        "formula": "[verb] volitional + か",
        "note": "Offer to do something, or propose doing it together. The volitional form + か = “shall I / shall we?”",
        "examples": [
            {
                "jp": "<ruby>窓<rt>まど</rt></ruby>を<ruby>開<rt>あ</rt></ruby>けましょうか。",
                "romaji": "Mado o akemashou ka.",
                "en": "Shall I open the window?",
                "zh": "我来开窗户吧？",
                "pinyin": "Wǒ lái kāi chuānghu ba?",
                "bd": [("窓", "window"), ("を", "[object]"), ("開けましょうか", "shall I open?")],
            },
            {
                "jp": "そろそろ<ruby>行<rt>い</rt></ruby>きましょうか。",
                "romaji": "Sorosoro ikimashou ka.",
                "en": "Shall we get going soon?",
                "zh": "我们差不多该走了吧？",
                "pinyin": "Wǒmen chàbuduō gāi zǒu le ba?",
                "bd": [("そろそろ", "soon / about now"), ("行きましょうか", "shall we go?")],
            },
        ],
    },
    {
        "num": 28,
        "jp": "〜と<ruby>思<rt>おも</rt></ruby>います",
        "romaji": "~ to omoimasu",
        "name": "I think that ~",
        "formula": "[plain-form clause] + と + 思います",
        "note": "State an opinion or guess. Put a plain-form clause before と思います = “I think that ~.”",
        "examples": [
            {
                "jp": "<ruby>明日<rt>あした</rt></ruby>は<ruby>晴<rt>は</rt></ruby>れると<ruby>思<rt>おも</rt></ruby>います。",
                "romaji": "Ashita wa hareru to omoimasu.",
                "en": "I think it'll be sunny tomorrow.",
                "zh": "我觉得明天会晴。",
                "pinyin": "Wǒ juéde míngtiān huì qíng.",
                "bd": [("明日", "tomorrow"), ("は", "topic"), ("晴れる", "clear up"), ("と", "that"), ("思います", "think")],
            },
            {
                "jp": "それはいい<ruby>考<rt>かんが</rt></ruby>えだと<ruby>思<rt>おも</rt></ruby>います。",
                "romaji": "Sore wa ii kangae da to omoimasu.",
                "en": "I think that's a good idea.",
                "zh": "我觉得那是个好主意。",
                "pinyin": "Wǒ juéde nà shì ge hǎo zhǔyi.",
                "bd": [("それ", "that"), ("は", "topic"), ("いい", "good"), ("考え", "idea"), ("だ", "is"), ("と", "that"), ("思います", "think")],
            },
        ],
    },
    {
        "num": 29,
        "jp": "〜といいですね",
        "romaji": "~ to ii desu ne",
        "name": "I hope ~ / it'd be nice if ~",
        "formula": "[plain-form clause] + といいですね",
        "note": "Express a hope for someone. A plain clause + といいですね = “it'd be good if ~, wouldn't it.”",
        "examples": [
            {
                "jp": "<ruby>明日<rt>あした</rt></ruby><ruby>晴<rt>は</rt></ruby>れるといいですね。",
                "romaji": "Ashita hareru to ii desu ne.",
                "en": "I hope it's sunny tomorrow.",
                "zh": "希望明天是晴天。",
                "pinyin": "Xīwàng míngtiān shì qíngtiān.",
                "bd": [("明日", "tomorrow"), ("晴れる", "clear up"), ("と", "if"), ("いい", "good"), ("です", "is"), ("ね", "isn't it")],
            },
            {
                "jp": "<ruby>早<rt>はや</rt></ruby>く<ruby>良<rt>よ</rt></ruby>くなるといいですね。",
                "romaji": "Hayaku yoku naru to ii desu ne.",
                "en": "I hope you get better soon.",
                "zh": "希望你早点好起来。",
                "pinyin": "Xīwàng nǐ zǎodiǎn hǎo qǐlái.",
                "bd": [("早く", "soon"), ("良くなる", "get better"), ("と", "if"), ("いい", "good"), ("です", "is"), ("ね", "isn't it")],
            },
        ],
    },
    {
        "num": 30,
        "jp": "<ruby>前<rt>まえ</rt></ruby>は〜しました",
        "romaji": "Mae wa ~ shimashita",
        "name": "before, I (used to) ~",
        "formula": "前は + [verb stem] + ました",
        "note": "Talk about what you did in the past, contrasting with now. 前は = “before / previously.”",
        "examples": [
            {
                "jp": "<ruby>前<rt>まえ</rt></ruby>はよくジョギングをしました。",
                "romaji": "Mae wa yoku jogingu o shimashita.",
                "en": "I used to go jogging a lot.",
                "zh": "我以前常去跑步。",
                "pinyin": "Wǒ yǐqián cháng qù pǎobù.",
                "bd": [("前", "before"), ("は", "topic"), ("よく", "often"), ("ジョギング", "jogging"), ("を", "[object]"), ("しました", "did")],
            },
            {
                "jp": "<ruby>前<rt>まえ</rt></ruby>は<ruby>中国<rt>ちゅうごく</rt></ruby>に<ruby>留学<rt>りゅうがく</rt></ruby>しました。",
                "romaji": "Mae wa Chuugoku ni ryuugaku shimashita.",
                "en": "I studied abroad in China before.",
                "zh": "我以前在中国留学过。",
                "pinyin": "Wǒ yǐqián zài Zhōngguó liúxuéguò.",
                "bd": [("前", "before"), ("は", "topic"), ("中国", "China"), ("に", "in"), ("留学しました", "studied abroad")],
            },
        ],
    },
    {
        "num": 31,
        "jp": "よく〜します",
        "romaji": "yoku ~ shimasu",
        "name": "often do ~",
        "formula": "よく + [verb]-ます",
        "note": "Describe a frequent habit. よく in front of a verb = “often.”",
        "examples": [
            {
                "jp": "よく<ruby>公園<rt>こうえん</rt></ruby>を<ruby>散歩<rt>さんぽ</rt></ruby>します。",
                "romaji": "Yoku kouen o sanpo shimasu.",
                "en": "I often take walks in the park.",
                "zh": "我常常在公园散步。",
                "pinyin": "Wǒ chángcháng zài gōngyuán sànbù.",
                "bd": [("よく", "often"), ("公園", "park"), ("を", "[through]"), ("散歩します", "take a walk")],
            },
            {
                "jp": "<ruby>友達<rt>ともだち</rt></ruby>とよくカラオケに<ruby>行<rt>い</rt></ruby>きます。",
                "romaji": "Tomodachi to yoku karaoke ni ikimasu.",
                "en": "I often go to karaoke with friends.",
                "zh": "我常和朋友去唱卡拉OK。",
                "pinyin": "Wǒ cháng hé péngyou qù chàng kǎlā OK.",
                "bd": [("友達", "friend"), ("と", "with"), ("よく", "often"), ("カラオケ", "karaoke"), ("に", "to"), ("行きます", "go")],
            },
        ],
    },
    {
        "num": 32,
        "jp": "〜しやすいです",
        "romaji": "~ shiyasui desu",
        "name": "easy to do ~",
        "formula": "[verb stem] + やすいです",
        "note": "Say something is easy to do. Attach やすい to the verb stem.",
        "examples": [
            {
                "jp": "この<ruby>本<rt>ほん</rt></ruby>は<ruby>読<rt>よ</rt></ruby>みやすいです。",
                "romaji": "Kono hon wa yomiyasui desu.",
                "en": "This book is easy to read.",
                "zh": "这本书很好读。",
                "pinyin": "Zhè běn shū hěn hǎo dú.",
                "bd": [("この", "this"), ("本", "book"), ("は", "topic"), ("読みやすい", "easy to read"), ("です", "is")],
            },
            {
                "jp": "この<ruby>町<rt>まち</rt></ruby>は<ruby>住<rt>す</rt></ruby>みやすいです。",
                "romaji": "Kono machi wa sumiyasui desu.",
                "en": "This town is easy to live in.",
                "zh": "这个城市很宜居。",
                "pinyin": "Zhège chéngshì hěn yíjū.",
                "bd": [("この", "this"), ("町", "town"), ("は", "topic"), ("住みやすい", "easy to live in"), ("です", "is")],
            },
        ],
    },
    {
        "num": 33,
        "jp": "〜しづらいです",
        "romaji": "~ shizurai desu",
        "name": "hard to do ~",
        "formula": "[verb stem] + づらいです",
        "note": "Say something is difficult or uncomfortable to do. Attach づらい (or にくい) to the verb stem — the opposite of やすい.",
        "examples": [
            {
                "jp": "この<ruby>字<rt>じ</rt></ruby>は<ruby>読<rt>よ</rt></ruby>みづらいです。",
                "romaji": "Kono ji wa yomizurai desu.",
                "en": "This handwriting is hard to read.",
                "zh": "这个字很难认。",
                "pinyin": "Zhège zì hěn nán rèn.",
                "bd": [("この", "this"), ("字", "character"), ("は", "topic"), ("読みづらい", "hard to read"), ("です", "is")],
            },
            {
                "jp": "この<ruby>靴<rt>くつ</rt></ruby>は<ruby>歩<rt>ある</rt></ruby>きづらいです。",
                "romaji": "Kono kutsu wa arukizurai desu.",
                "en": "These shoes are hard to walk in.",
                "zh": "这双鞋走起来不舒服。",
                "pinyin": "Zhè shuāng xié zǒu qǐlái bù shūfu.",
                "bd": [("この", "this"), ("靴", "shoes"), ("は", "topic"), ("歩きづらい", "hard to walk in"), ("です", "is")],
            },
        ],
    },
    {
        "num": 34,
        "jp": "〜が<ruby>好<rt>す</rt></ruby>きです",
        "romaji": "~ ga suki desu",
        "name": "like ~",
        "formula": "[thing] が + 好きです",
        "note": "Say what you like. The thing you like is marked by が, not を. 好き is a な-adjective meaning “likable.”",
        "examples": [
            {
                "jp": "<ruby>私<rt>わたし</rt></ruby>は<ruby>犬<rt>いぬ</rt></ruby>が<ruby>好<rt>す</rt></ruby>きです。",
                "romaji": "Watashi wa inu ga suki desu.",
                "en": "I like dogs.",
                "zh": "我喜欢狗。",
                "pinyin": "Wǒ xǐhuan gǒu.",
                "bd": [("私", "I"), ("は", "topic"), ("犬", "dog"), ("が", "[subject]"), ("好き", "likable"), ("です", "is")],
            },
            {
                "jp": "<ruby>音楽<rt>おんがく</rt></ruby>を<ruby>聞<rt>き</rt></ruby>くのが<ruby>好<rt>す</rt></ruby>きです。",
                "romaji": "Ongaku o kiku no ga suki desu.",
                "en": "I like listening to music.",
                "zh": "我喜欢听音乐。",
                "pinyin": "Wǒ xǐhuan tīng yīnyuè.",
                "bd": [("音楽", "music"), ("を", "[object]"), ("聞く", "listen"), ("の", "the act of"), ("が", "[subject]"), ("好き", "likable"), ("です", "is")],
            },
        ],
    },
    {
        "num": 35,
        "jp": "〜がほしいです",
        "romaji": "~ ga hoshii desu",
        "name": "want ~ (a thing)",
        "formula": "[noun] が + ほしいです",
        "note": "Express that you want an object. The thing wanted takes が. (For wanting to do an action, use 〜したい, #8.)",
        "examples": [
            {
                "jp": "<ruby>新<rt>あたら</rt></ruby>しいパソコンがほしいです。",
                "romaji": "Atarashii pasokon ga hoshii desu.",
                "en": "I want a new computer.",
                "zh": "我想要一台新电脑。",
                "pinyin": "Wǒ xiǎng yào yì tái xīn diànnǎo.",
                "bd": [("新しい", "new"), ("パソコン", "computer"), ("が", "[subject]"), ("ほしい", "wanted"), ("です", "is")],
            },
            {
                "jp": "<ruby>時間<rt>じかん</rt></ruby>がほしいです。",
                "romaji": "Jikan ga hoshii desu.",
                "en": "I want (more) time.",
                "zh": "我想要点时间。",
                "pinyin": "Wǒ xiǎng yào diǎn shíjiān.",
                "bd": [("時間", "time"), ("が", "[subject]"), ("ほしい", "wanted"), ("です", "is")],
            },
        ],
    },
    {
        "num": 36,
        "jp": "〜が<ruby>必要<rt>ひつよう</rt></ruby>です",
        "romaji": "~ ga hitsuyou desu",
        "name": "need ~",
        "formula": "[noun] が + 必要です",
        "note": "Say that something is necessary. The needed thing takes が; 必要 is a な-adjective meaning “necessary.”",
        "examples": [
            {
                "jp": "パスポートが<ruby>必要<rt>ひつよう</rt></ruby>です。",
                "romaji": "Pasupooto ga hitsuyou desu.",
                "en": "You need a passport.",
                "zh": "需要护照。",
                "pinyin": "Xūyào hùzhào.",
                "bd": [("パスポート", "passport"), ("が", "[subject]"), ("必要", "necessary"), ("です", "is")],
            },
            {
                "jp": "もう<ruby>少<rt>すこ</rt></ruby>し<ruby>時間<rt>じかん</rt></ruby>が<ruby>必要<rt>ひつよう</rt></ruby>です。",
                "romaji": "Mou sukoshi jikan ga hitsuyou desu.",
                "en": "I need a little more time.",
                "zh": "我需要再多一点时间。",
                "pinyin": "Wǒ xūyào zài duō yìdiǎn shíjiān.",
                "bd": [("もう少し", "a little more"), ("時間", "time"), ("が", "[subject]"), ("必要", "necessary"), ("です", "is")],
            },
        ],
    },
    {
        "num": 37,
        "jp": "〜だそうです",
        "romaji": "~ da sou desu",
        "name": "I hear that ~ (hearsay)",
        "formula": "[plain-form clause] + そうです",
        "note": "Report something you heard or read. Attach そうです to a plain-form clause = “I hear / they say that ~.”",
        "examples": [
            {
                "jp": "<ruby>田中<rt>たなか</rt></ruby>さんは<ruby>来月<rt>らいげつ</rt></ruby><ruby>結婚<rt>けっこん</rt></ruby>するそうです。",
                "romaji": "Tanaka-san wa raigetsu kekkon suru sou desu.",
                "en": "I hear Mr. Tanaka is getting married next month.",
                "zh": "听说田中下个月要结婚。",
                "pinyin": "Tīngshuō Tiánzhōng xià ge yuè yào jiéhūn.",
                "bd": [("田中さん", "Mr. Tanaka"), ("は", "topic"), ("来月", "next month"), ("結婚する", "get married"), ("そうです", "I hear")],
            },
            {
                "jp": "あの<ruby>店<rt>みせ</rt></ruby>は<ruby>安<rt>やす</rt></ruby>いそうです。",
                "romaji": "Ano mise wa yasui sou desu.",
                "en": "I hear that shop is cheap.",
                "zh": "听说那家店很便宜。",
                "pinyin": "Tīngshuō nà jiā diàn hěn piányi.",
                "bd": [("あの", "that"), ("店", "shop"), ("は", "topic"), ("安い", "cheap"), ("そうです", "I hear")],
            },
        ],
    },
    {
        "num": 38,
        "jp": "〜らしい",
        "romaji": "~ rashii",
        "name": "apparently / seems ~",
        "formula": "[plain-form clause] + らしい",
        "note": "Say something seems true based on what you've heard or gathered. らしい reports indirect, secondhand information.",
        "examples": [
            {
                "jp": "<ruby>彼<rt>かれ</rt></ruby>は<ruby>今日<rt>きょう</rt></ruby><ruby>休<rt>やす</rt></ruby>むらしい。",
                "romaji": "Kare wa kyou yasumu rashii.",
                "en": "Apparently he's off today.",
                "zh": "他今天好像请假。",
                "pinyin": "Tā jīntiān hǎoxiàng qǐngjià.",
                "bd": [("彼", "he"), ("は", "topic"), ("今日", "today"), ("休む", "take off / rest"), ("らしい", "apparently")],
            },
            {
                "jp": "あの<ruby>映画<rt>えいが</rt></ruby>は<ruby>面白<rt>おもしろ</rt></ruby>いらしいです。",
                "romaji": "Ano eiga wa omoshiroi rashii desu.",
                "en": "That movie is supposedly interesting.",
                "zh": "听说那部电影很有意思。",
                "pinyin": "Tīngshuō nà bù diànyǐng hěn yǒuyìsi.",
                "bd": [("あの", "that"), ("映画", "movie"), ("は", "topic"), ("面白い", "interesting"), ("らしい", "seems"), ("です", "(polite)")],
            },
        ],
    },
    {
        "num": 39,
        "jp": "〜のようです",
        "romaji": "~ no you desu",
        "name": "it seems like ~ / as if ~",
        "formula": "[noun] のよう / [plain clause] + ようです",
        "note": "Say something appears to be the case, based on your own impression. With a noun, use のよう.",
        "examples": [
            {
                "jp": "<ruby>外<rt>そと</rt></ruby>は<ruby>雨<rt>あめ</rt></ruby>のようです。",
                "romaji": "Soto wa ame no you desu.",
                "en": "It looks like it's raining outside.",
                "zh": "外面好像下雨了。",
                "pinyin": "Wàimiàn hǎoxiàng xià yǔ le.",
                "bd": [("外", "outside"), ("は", "topic"), ("雨", "rain"), ("のよう", "like / seems"), ("です", "is")],
            },
            {
                "jp": "<ruby>彼<rt>かれ</rt></ruby>は<ruby>疲<rt>つか</rt></ruby>れているようです。",
                "romaji": "Kare wa tsukarete iru you desu.",
                "en": "He seems to be tired.",
                "zh": "他好像很累。",
                "pinyin": "Tā hǎoxiàng hěn lèi.",
                "bd": [("彼", "he"), ("は", "topic"), ("疲れている", "is tired"), ("ようです", "seems")],
            },
        ],
    },
    {
        "num": 40,
        "jp": "〜そうです",
        "romaji": "~ sou desu",
        "name": "looks ~ (from appearance)",
        "formula": "[verb stem / adj stem] + そうです",
        "note": "Make a guess from what you see. Attach そう to a verb or adjective stem = “looks like / seems about to.” (Different from hearsay そう in #37.)",
        "examples": [
            {
                "jp": "<ruby>雨<rt>あめ</rt></ruby>が<ruby>降<rt>ふ</rt></ruby>りそうです。",
                "romaji": "Ame ga furisou desu.",
                "en": "It looks like it's going to rain.",
                "zh": "看样子要下雨了。",
                "pinyin": "Kàn yàngzi yào xià yǔ le.",
                "bd": [("雨", "rain"), ("が", "[subject]"), ("降りそう", "looks about to fall"), ("です", "is")],
            },
            {
                "jp": "このケーキはおいしそうです。",
                "romaji": "Kono keeki wa oishisou desu.",
                "en": "This cake looks delicious.",
                "zh": "这个蛋糕看起来很好吃。",
                "pinyin": "Zhège dàngāo kàn qǐlái hěn hǎochī.",
                "bd": [("この", "this"), ("ケーキ", "cake"), ("は", "topic"), ("おいしそう", "looks tasty"), ("です", "is")],
            },
        ],
    },
    {
        "num": 41,
        "jp": "〜するはずです",
        "romaji": "~ suru hazu desu",
        "name": "should / ought to ~ (expectation)",
        "formula": "[plain form] + はずです",
        "note": "State a logical expectation — what should be true based on reasoning. はず = “supposed to / expected to.”",
        "examples": [
            {
                "jp": "<ruby>彼<rt>かれ</rt></ruby>はもうすぐ<ruby>来<rt>く</rt></ruby>るはずです。",
                "romaji": "Kare wa mou sugu kuru hazu desu.",
                "en": "He should be here soon.",
                "zh": "他应该马上就来。",
                "pinyin": "Tā yīnggāi mǎshàng jiù lái.",
                "bd": [("彼", "he"), ("は", "topic"), ("もうすぐ", "soon"), ("来る", "come"), ("はず", "supposed to"), ("です", "is")],
            },
            {
                "jp": "<ruby>鍵<rt>かぎ</rt></ruby>はかばんの<ruby>中<rt>なか</rt></ruby>にあるはずです。",
                "romaji": "Kagi wa kaban no naka ni aru hazu desu.",
                "en": "The key should be in the bag.",
                "zh": "钥匙应该在包里。",
                "pinyin": "Yàoshi yīnggāi zài bāo lǐ.",
                "bd": [("鍵", "key"), ("は", "topic"), ("かばん", "bag"), ("の", "'s"), ("中", "inside"), ("に", "in"), ("ある", "be"), ("はず", "supposed to"), ("です", "is")],
            },
        ],
    },
    {
        "num": 42,
        "jp": "〜すぎます",
        "romaji": "~ sugimasu",
        "name": "too much ~ / over-do",
        "formula": "[verb stem / adj stem] + すぎます",
        "note": "Say something is excessive. Attach すぎる to a verb or adjective stem = “too / overly.”",
        "examples": [
            {
                "jp": "<ruby>食<rt>た</rt></ruby>べすぎました。",
                "romaji": "Tabesugimashita.",
                "en": "I ate too much.",
                "zh": "我吃太多了。",
                "pinyin": "Wǒ chī tài duō le.",
                "bd": [("食べすぎました", "ate too much")],
            },
            {
                "jp": "この<ruby>問題<rt>もんだい</rt></ruby>は<ruby>難<rt>むずか</rt></ruby>しすぎます。",
                "romaji": "Kono mondai wa muzukashisugimasu.",
                "en": "This problem is too difficult.",
                "zh": "这个问题太难了。",
                "pinyin": "Zhège wèntí tài nán le.",
                "bd": [("この", "this"), ("問題", "problem"), ("は", "topic"), ("難しすぎます", "is too difficult")],
            },
        ],
    },
    {
        "num": 43,
        "jp": "…より〜です",
        "romaji": "... yori ~ desu",
        "name": "more ~ than … (comparison)",
        "formula": "A は B より + [adjective] + です",
        "note": "Compare two things. “A は B より [adjective]” = “A is more [adjective] than B.” より = “than.”",
        "examples": [
            {
                "jp": "<ruby>飛行機<rt>ひこうき</rt></ruby>は<ruby>電車<rt>でんしゃ</rt></ruby>より<ruby>速<rt>はや</rt></ruby>いです。",
                "romaji": "Hikouki wa densha yori hayai desu.",
                "en": "Planes are faster than trains.",
                "zh": "飞机比火车快。",
                "pinyin": "Fēijī bǐ huǒchē kuài.",
                "bd": [("飛行機", "airplane"), ("は", "topic"), ("電車", "train"), ("より", "than"), ("速い", "fast"), ("です", "is")],
            },
            {
                "jp": "<ruby>今日<rt>きょう</rt></ruby>は<ruby>昨日<rt>きのう</rt></ruby>より<ruby>暑<rt>あつ</rt></ruby>いです。",
                "romaji": "Kyou wa kinou yori atsui desu.",
                "en": "Today is hotter than yesterday.",
                "zh": "今天比昨天热。",
                "pinyin": "Jīntiān bǐ zuótiān rè.",
                "bd": [("今日", "today"), ("は", "topic"), ("昨日", "yesterday"), ("より", "than"), ("暑い", "hot"), ("です", "is")],
            },
        ],
    },
    {
        "num": 44,
        "jp": "〜かもしれません",
        "romaji": "~ kamoshiremasen",
        "name": "might / maybe ~",
        "formula": "[plain form] + かもしれません",
        "note": "Express possibility — something that may or may not be true. Attach かもしれません to a plain-form clause.",
        "examples": [
            {
                "jp": "<ruby>明日<rt>あした</rt></ruby>は<ruby>雪<rt>ゆき</rt></ruby>が<ruby>降<rt>ふ</rt></ruby>るかもしれません。",
                "romaji": "Ashita wa yuki ga furu kamoshiremasen.",
                "en": "It might snow tomorrow.",
                "zh": "明天可能会下雪。",
                "pinyin": "Míngtiān kěnéng huì xià xuě.",
                "bd": [("明日", "tomorrow"), ("は", "topic"), ("雪", "snow"), ("が", "[subject]"), ("降る", "fall"), ("かもしれません", "might")],
            },
            {
                "jp": "<ruby>彼<rt>かれ</rt></ruby>は<ruby>知<rt>し</rt></ruby>らないかもしれません。",
                "romaji": "Kare wa shiranai kamoshiremasen.",
                "en": "He might not know.",
                "zh": "他可能不知道。",
                "pinyin": "Tā kěnéng bù zhīdào.",
                "bd": [("彼", "he"), ("は", "topic"), ("知らない", "not know"), ("かもしれません", "might")],
            },
        ],
    },
    {
        "num": 45,
        "jp": "〜してしまいました",
        "romaji": "~ shiteshimaimashita",
        "name": "ended up ~ / did ~ (regret)",
        "formula": "[verb] て-form + しまいました",
        "note": "Show that an action was completed — often by accident or with regret. て-form + しまいました.",
        "examples": [
            {
                "jp": "<ruby>財布<rt>さいふ</rt></ruby>を<ruby>忘<rt>わす</rt></ruby>れてしまいました。",
                "romaji": "Saifu o wasurete shimaimashita.",
                "en": "I (carelessly) forgot my wallet.",
                "zh": "我把钱包忘了。",
                "pinyin": "Wǒ bǎ qiánbāo wàng le.",
                "bd": [("財布", "wallet"), ("を", "[object]"), ("忘れてしまいました", "ended up forgetting")],
            },
            {
                "jp": "<ruby>全部<rt>ぜんぶ</rt></ruby><ruby>食<rt>た</rt></ruby>べてしまいました。",
                "romaji": "Zenbu tabete shimaimashita.",
                "en": "I ate it all up.",
                "zh": "我全都吃光了。",
                "pinyin": "Wǒ quán dōu chīguāng le.",
                "bd": [("全部", "all"), ("食べてしまいました", "ate up completely")],
            },
        ],
    },
    {
        "num": 46,
        "jp": "〜したところです",
        "romaji": "~ shita tokoro desu",
        "name": "just did ~ / just finished",
        "formula": "[verb] past-plain + ところです",
        "note": "Say you've just finished doing something. Past-plain verb + ところです marks the moment right after an action.",
        "examples": [
            {
                "jp": "<ruby>今<rt>いま</rt></ruby>、<ruby>駅<rt>えき</rt></ruby>に<ruby>着<rt>つ</rt></ruby>いたところです。",
                "romaji": "Ima, eki ni tsuita tokoro desu.",
                "en": "I've just arrived at the station.",
                "zh": "我刚到车站。",
                "pinyin": "Wǒ gāng dào chēzhàn.",
                "bd": [("今", "now"), ("駅", "station"), ("に", "at"), ("着いた", "arrived"), ("ところ", "the point/moment"), ("です", "is")],
            },
            {
                "jp": "ご<ruby>飯<rt>はん</rt></ruby>を<ruby>食<rt>た</rt></ruby>べたところです。",
                "romaji": "Gohan o tabeta tokoro desu.",
                "en": "I've just eaten.",
                "zh": "我刚吃完饭。",
                "pinyin": "Wǒ gāng chīwán fàn.",
                "bd": [("ご飯", "meal"), ("を", "[object]"), ("食べた", "ate"), ("ところ", "the point/moment"), ("です", "is")],
            },
        ],
    },
    {
        "num": 47,
        "jp": "〜しなさい",
        "romaji": "~ shinasai",
        "name": "do ~! (gentle command)",
        "formula": "[verb stem] + なさい",
        "note": "A firm but caring command, typically from a parent or teacher to a child. Attach なさい to the verb stem.",
        "examples": [
            {
                "jp": "<ruby>早<rt>はや</rt></ruby>く<ruby>寝<rt>ね</rt></ruby>なさい。",
                "romaji": "Hayaku nenasai.",
                "en": "Go to bed early.",
                "zh": "早点睡觉。",
                "pinyin": "Zǎodiǎn shuìjiào.",
                "bd": [("早く", "early"), ("寝なさい", "go to sleep (command)")],
            },
            {
                "jp": "<ruby>宿題<rt>しゅくだい</rt></ruby>をしなさい。",
                "romaji": "Shukudai o shinasai.",
                "en": "Do your homework.",
                "zh": "去做作业。",
                "pinyin": "Qù zuò zuòyè.",
                "bd": [("宿題", "homework"), ("を", "[object]"), ("しなさい", "do (command)")],
            },
        ],
    },
    {
        "num": 48,
        "jp": "あまり〜ない",
        "romaji": "amari ~ nai",
        "name": "not very ~ / not much",
        "formula": "あまり + [negative]",
        "note": "Soften a negative statement. あまり paired with a negative = “not very / not much.”",
        "examples": [
            {
                "jp": "あまりお<ruby>酒<rt>さけ</rt></ruby>を<ruby>飲<rt>の</rt></ruby>みません。",
                "romaji": "Amari osake o nomimasen.",
                "en": "I don't drink much alcohol.",
                "zh": "我不太喝酒。",
                "pinyin": "Wǒ bú tài hē jiǔ.",
                "bd": [("あまり", "(not) much"), ("お酒", "alcohol"), ("を", "[object]"), ("飲みません", "don't drink")],
            },
            {
                "jp": "この<ruby>料理<rt>りょうり</rt></ruby>はあまり<ruby>辛<rt>から</rt></ruby>くないです。",
                "romaji": "Kono ryouri wa amari karakunai desu.",
                "en": "This dish isn't very spicy.",
                "zh": "这道菜不太辣。",
                "pinyin": "Zhè dào cài bú tài là.",
                "bd": [("この", "this"), ("料理", "dish"), ("は", "topic"), ("あまり", "not very"), ("辛くない", "not spicy"), ("です", "is")],
            },
        ],
    },
    {
        "num": 49,
        "jp": "それほど〜ない",
        "romaji": "sorehodo ~ nai",
        "name": "not so ~ / not that ~",
        "formula": "それほど + [negative]",
        "note": "Say something is “not that ~,” often gently lowering an expectation. それほど + negative.",
        "examples": [
            {
                "jp": "<ruby>今日<rt>きょう</rt></ruby>はそれほど<ruby>寒<rt>さむ</rt></ruby>くないです。",
                "romaji": "Kyou wa sorehodo samukunai desu.",
                "en": "It's not that cold today.",
                "zh": "今天没那么冷。",
                "pinyin": "Jīntiān méi nàme lěng.",
                "bd": [("今日", "today"), ("は", "topic"), ("それほど", "that much"), ("寒くない", "not cold"), ("です", "is")],
            },
            {
                "jp": "その<ruby>映画<rt>えいが</rt></ruby>はそれほど<ruby>面白<rt>おもしろ</rt></ruby>くなかったです。",
                "romaji": "Sono eiga wa sorehodo omoshiroku nakatta desu.",
                "en": "That movie wasn't that interesting.",
                "zh": "那部电影没那么有意思。",
                "pinyin": "Nà bù diànyǐng méi nàme yǒuyìsi.",
                "bd": [("その", "that"), ("映画", "movie"), ("は", "topic"), ("それほど", "that much"), ("面白くなかった", "wasn't interesting"), ("です", "(polite)")],
            },
        ],
    },
    {
        "num": 50,
        "jp": "よく〜",
        "romaji": "yoku ~",
        "name": "well / a lot ~",
        "formula": "よく + [verb]",
        "note": "Besides “often” (#31), よく also means “well” or “thoroughly.” Context tells you which: frequency or quality.",
        "examples": [
            {
                "jp": "よく<ruby>眠<rt>ねむ</rt></ruby>れました。",
                "romaji": "Yoku nemuremashita.",
                "en": "I slept well.",
                "zh": "我睡得很好。",
                "pinyin": "Wǒ shuì de hěn hǎo.",
                "bd": [("よく", "well"), ("眠れました", "was able to sleep")],
            },
            {
                "jp": "<ruby>先生<rt>せんせい</rt></ruby>の<ruby>話<rt>はなし</rt></ruby>をよく<ruby>聞<rt>き</rt></ruby>いてください。",
                "romaji": "Sensei no hanashi o yoku kiite kudasai.",
                "en": "Please listen carefully to the teacher.",
                "zh": "请认真听老师讲。",
                "pinyin": "Qǐng rènzhēn tīng lǎoshī jiǎng.",
                "bd": [("先生", "teacher"), ("の", "'s"), ("話", "talk"), ("を", "[object]"), ("よく", "closely / well"), ("聞いて", "listen"), ("ください", "please")],
            },
        ],
    },
    {
        "num": 51,
        "jp": "まったく〜ない",
        "romaji": "mattaku ~ nai",
        "name": "not at all ~",
        "formula": "まったく + [negative]",
        "note": "A strong, complete negative. まったく + negative = “not at all / not in the least.”",
        "examples": [
            {
                "jp": "<ruby>意味<rt>いみ</rt></ruby>がまったく<ruby>分<rt>わ</rt></ruby>かりません。",
                "romaji": "Imi ga mattaku wakarimasen.",
                "en": "I don't understand the meaning at all.",
                "zh": "我完全不懂意思。",
                "pinyin": "Wǒ wánquán bù dǒng yìsi.",
                "bd": [("意味", "meaning"), ("が", "[subject]"), ("まったく", "at all"), ("分かりません", "don't understand")],
            },
            {
                "jp": "お<ruby>金<rt>かね</rt></ruby>がまったくありません。",
                "romaji": "Okane ga mattaku arimasen.",
                "en": "I have no money at all.",
                "zh": "我一点钱都没有。",
                "pinyin": "Wǒ yìdiǎn qián dōu méiyǒu.",
                "bd": [("お金", "money"), ("が", "[subject]"), ("まったく", "at all"), ("ありません", "there isn't")],
            },
        ],
    },
    {
        "num": 52,
        "jp": "〜させてください",
        "romaji": "~ sasete kudasai",
        "name": "please let me ~",
        "formula": "[verb] causative て-form + ください",
        "note": "Ask permission to do something yourself. The causative て-form + ください = “please let me ~.”",
        "examples": [
            {
                "jp": "ここで<ruby>写真<rt>しゃしん</rt></ruby>を<ruby>撮<rt>と</rt></ruby>らせてください。",
                "romaji": "Koko de shashin o torasete kudasai.",
                "en": "Please let me take a photo here.",
                "zh": "请让我在这里拍张照。",
                "pinyin": "Qǐng ràng wǒ zài zhèlǐ pāi zhāng zhào.",
                "bd": [("ここ", "here"), ("で", "at"), ("写真", "photo"), ("を", "[object]"), ("撮らせて", "let (me) take"), ("ください", "please")],
            },
            {
                "jp": "<ruby>少<rt>すこ</rt></ruby>し<ruby>考<rt>かんが</rt></ruby>えさせてください。",
                "romaji": "Sukoshi kangaesasete kudasai.",
                "en": "Please let me think for a moment.",
                "zh": "请让我想一下。",
                "pinyin": "Qǐng ràng wǒ xiǎng yíxià.",
                "bd": [("少し", "a little"), ("考えさせて", "let (me) think"), ("ください", "please")],
            },
        ],
    },
    {
        "num": 53,
        "jp": "〜させます",
        "romaji": "~ sasemasu",
        "name": "make / let someone ~ (causative)",
        "formula": "[person] に + [verb] causative + ます",
        "note": "Cause someone to do something — make or let them. The person who acts is marked by に.",
        "examples": [
            {
                "jp": "<ruby>母<rt>はは</rt></ruby>は<ruby>弟<rt>おとうと</rt></ruby>に<ruby>部屋<rt>へや</rt></ruby>を<ruby>掃除<rt>そうじ</rt></ruby>させます。",
                "romaji": "Haha wa otouto ni heya o souji sasemasu.",
                "en": "My mother makes my little brother clean the room.",
                "zh": "妈妈让弟弟打扫房间。",
                "pinyin": "Māma ràng dìdi dǎsǎo fángjiān.",
                "bd": [("母", "mother"), ("は", "topic"), ("弟", "little brother"), ("に", "[causee]"), ("部屋", "room"), ("を", "[object]"), ("掃除させます", "makes (him) clean")],
            },
            {
                "jp": "<ruby>先生<rt>せんせい</rt></ruby>は<ruby>学生<rt>がくせい</rt></ruby>に<ruby>本<rt>ほん</rt></ruby>を<ruby>読<rt>よ</rt></ruby>ませます。",
                "romaji": "Sensei wa gakusei ni hon o yomasemasu.",
                "en": "The teacher has the students read a book.",
                "zh": "老师让学生读书。",
                "pinyin": "Lǎoshī ràng xuésheng dúshū.",
                "bd": [("先生", "teacher"), ("は", "topic"), ("学生", "student"), ("に", "[causee]"), ("本", "book"), ("を", "[object]"), ("読ませます", "makes (them) read")],
            },
        ],
    },
    {
        "num": 54,
        "jp": "〜されました",
        "romaji": "~ saremashita",
        "name": "was done to me (passive past)",
        "formula": "[verb] passive + ました",
        "note": "The passive — something was done to the subject, often unwanted. The doer is marked by に.",
        "examples": [
            {
                "jp": "<ruby>財布<rt>さいふ</rt></ruby>を<ruby>盗<rt>ぬす</rt></ruby>まれました。",
                "romaji": "Saifu o nusumaremashita.",
                "en": "My wallet was stolen.",
                "zh": "我的钱包被偷了。",
                "pinyin": "Wǒ de qiánbāo bèi tōu le.",
                "bd": [("財布", "wallet"), ("を", "[object]"), ("盗まれました", "was stolen")],
            },
            {
                "jp": "<ruby>先生<rt>せんせい</rt></ruby>に<ruby>褒<rt>ほ</rt></ruby>められました。",
                "romaji": "Sensei ni homeraremashita.",
                "en": "I was praised by the teacher.",
                "zh": "我被老师表扬了。",
                "pinyin": "Wǒ bèi lǎoshī biǎoyáng le.",
                "bd": [("先生", "teacher"), ("に", "by"), ("褒められました", "was praised")],
            },
        ],
    },
    {
        "num": 55,
        "jp": "〜するつもりです",
        "romaji": "~ suru tsumori desu",
        "name": "intend to ~ / plan to ~",
        "formula": "[dictionary form] + つもりです",
        "note": "State an intention or plan you've decided on. Dictionary-form verb + つもりです.",
        "examples": [
            {
                "jp": "<ruby>来年<rt>らいねん</rt></ruby><ruby>日本<rt>にほん</rt></ruby>に<ruby>留学<rt>りゅうがく</rt></ruby>するつもりです。",
                "romaji": "Rainen Nihon ni ryuugaku suru tsumori desu.",
                "en": "I plan to study in Japan next year.",
                "zh": "我打算明年去日本留学。",
                "pinyin": "Wǒ dǎsuàn míngnián qù Rìběn liúxué.",
                "bd": [("来年", "next year"), ("日本", "Japan"), ("に", "in"), ("留学する", "study abroad"), ("つもり", "intention"), ("です", "is")],
            },
            {
                "jp": "<ruby>週末<rt>しゅうまつ</rt></ruby>は<ruby>家<rt>いえ</rt></ruby>にいるつもりです。",
                "romaji": "Shuumatsu wa ie ni iru tsumori desu.",
                "en": "I intend to stay home this weekend.",
                "zh": "周末我打算待在家里。",
                "pinyin": "Zhōumò wǒ dǎsuàn dāi zài jiā lǐ.",
                "bd": [("週末", "weekend"), ("は", "topic"), ("家", "home"), ("に", "at"), ("いる", "stay"), ("つもり", "intention"), ("です", "is")],
            },
        ],
    },
    {
        "num": 56,
        "jp": "〜が<ruby>得意<rt>とくい</rt></ruby>（<ruby>苦手<rt>にがて</rt></ruby>）です",
        "romaji": "~ ga tokui (nigate) desu",
        "name": "good (bad) at ~",
        "formula": "[skill] が + 得意 / 苦手 + です",
        "note": "Say what you're good or bad at. 得意 = good at; 苦手 = poor at / not a fan of. The skill takes が.",
        "examples": [
            {
                "jp": "<ruby>私<rt>わたし</rt></ruby>は<ruby>料理<rt>りょうり</rt></ruby>が<ruby>得意<rt>とくい</rt></ruby>です。",
                "romaji": "Watashi wa ryouri ga tokui desu.",
                "en": "I'm good at cooking.",
                "zh": "我擅长做饭。",
                "pinyin": "Wǒ shàncháng zuòfàn.",
                "bd": [("私", "I"), ("は", "topic"), ("料理", "cooking"), ("が", "[subject]"), ("得意", "good at"), ("です", "is")],
            },
            {
                "jp": "<ruby>私<rt>わたし</rt></ruby>は<ruby>数学<rt>すうがく</rt></ruby>が<ruby>苦手<rt>にがて</rt></ruby>です。",
                "romaji": "Watashi wa suugaku ga nigate desu.",
                "en": "I'm bad at math.",
                "zh": "我不擅长数学。",
                "pinyin": "Wǒ bú shàncháng shùxué.",
                "bd": [("私", "I"), ("は", "topic"), ("数学", "math"), ("が", "[subject]"), ("苦手", "bad at"), ("です", "is")],
            },
        ],
    },
    {
        "num": 57,
        "jp": "〜しそうです",
        "romaji": "~ shisou desu",
        "name": "looks about to ~ (on the verge)",
        "formula": "[verb stem] + そうです",
        "note": "Say something looks about to happen any moment. Verb stem + そう, judged from appearance (like #40).",
        "examples": [
            {
                "jp": "ボタンが<ruby>取<rt>と</rt></ruby>れそうです。",
                "romaji": "Botan ga toresou desu.",
                "en": "The button looks like it's about to come off.",
                "zh": "扣子好像要掉了。",
                "pinyin": "Kòuzi hǎoxiàng yào diào le.",
                "bd": [("ボタン", "button"), ("が", "[subject]"), ("取れそう", "looks about to come off"), ("です", "is")],
            },
            {
                "jp": "<ruby>赤<rt>あか</rt></ruby>ちゃんが<ruby>泣<rt>な</rt></ruby>きそうです。",
                "romaji": "Akachan ga nakisou desu.",
                "en": "The baby looks like it's about to cry.",
                "zh": "宝宝好像要哭了。",
                "pinyin": "Bǎobao hǎoxiàng yào kū le.",
                "bd": [("赤ちゃん", "baby"), ("が", "[subject]"), ("泣きそう", "looks about to cry"), ("です", "is")],
            },
        ],
    },
    {
        "num": 58,
        "jp": "〜をどうぞ",
        "romaji": "~ wo douzo",
        "name": "here you go / please have ~",
        "formula": "[noun] を + どうぞ",
        "note": "Offer something to someone graciously. Noun + をどうぞ = “please, have ~ / here you are.”",
        "examples": [
            {
                "jp": "お<ruby>茶<rt>ちゃ</rt></ruby>をどうぞ。",
                "romaji": "Ocha o douzo.",
                "en": "Here's some tea.",
                "zh": "请喝茶。",
                "pinyin": "Qǐng hē chá.",
                "bd": [("お茶", "tea"), ("を", "[object]"), ("どうぞ", "please (here you are)")],
            },
            {
                "jp": "こちらをどうぞ。",
                "romaji": "Kochira o douzo.",
                "en": "This one, please. / Right this way.",
                "zh": "这边请。",
                "pinyin": "Zhèbiān qǐng.",
                "bd": [("こちら", "this way / this one"), ("を", "[object]"), ("どうぞ", "please")],
            },
        ],
    },
    {
        "num": 59,
        "jp": "どうぞ〜してください",
        "romaji": "Douzo ~ shite kudasai",
        "name": "please go ahead and ~",
        "formula": "どうぞ + [verb] て-form + ください",
        "note": "Warmly invite someone to do something. どうぞ adds “please, go ahead” to a normal て-form request.",
        "examples": [
            {
                "jp": "どうぞ<ruby>座<rt>すわ</rt></ruby>ってください。",
                "romaji": "Douzo suwatte kudasai.",
                "en": "Please, have a seat.",
                "zh": "请坐。",
                "pinyin": "Qǐng zuò.",
                "bd": [("どうぞ", "please / go ahead"), ("座って", "sit"), ("ください", "please")],
            },
            {
                "jp": "どうぞ<ruby>入<rt>はい</rt></ruby>ってください。",
                "romaji": "Douzo haitte kudasai.",
                "en": "Please come in.",
                "zh": "请进。",
                "pinyin": "Qǐng jìn.",
                "bd": [("どうぞ", "please / go ahead"), ("入って", "enter"), ("ください", "please")],
            },
        ],
    },
    {
        "num": 60,
        "jp": "どうも〜",
        "romaji": "Doumo ~",
        "name": "thanks / somehow / really ~",
        "formula": "どうも + [phrase]",
        "note": "どうも is versatile: a quick “thanks,” a vague “somehow,” or an intensifier “really.” Tone and context decide.",
        "examples": [
            {
                "jp": "どうもありがとうございます。",
                "romaji": "Doumo arigatou gozaimasu.",
                "en": "Thank you very much.",
                "zh": "非常感谢。",
                "pinyin": "Fēicháng gǎnxiè.",
                "bd": [("どうも", "very / much"), ("ありがとうございます", "thank you")],
            },
            {
                "jp": "どうも<ruby>風邪<rt>かぜ</rt></ruby>を<ruby>引<rt>ひ</rt></ruby>いたようです。",
                "romaji": "Doumo kaze o hiita you desu.",
                "en": "It seems I've somehow caught a cold.",
                "zh": "我好像感冒了。",
                "pinyin": "Wǒ hǎoxiàng gǎnmào le.",
                "bd": [("どうも", "somehow"), ("風邪", "cold"), ("を", "[object]"), ("引いた", "caught"), ("ようです", "seems")],
            },
        ],
    },
    {
        "num": 61,
        "jp": "とても〜",
        "romaji": "totemo ~",
        "name": "very ~",
        "formula": "とても + [adjective]",
        "note": "Intensify an adjective. とても = “very,” placed right before the adjective.",
        "examples": [
            {
                "jp": "この<ruby>料理<rt>りょうり</rt></ruby>はとてもおいしいです。",
                "romaji": "Kono ryouri wa totemo oishii desu.",
                "en": "This dish is very delicious.",
                "zh": "这道菜非常好吃。",
                "pinyin": "Zhè dào cài fēicháng hǎochī.",
                "bd": [("この", "this"), ("料理", "dish"), ("は", "topic"), ("とても", "very"), ("おいしい", "delicious"), ("です", "is")],
            },
            {
                "jp": "<ruby>今日<rt>きょう</rt></ruby>はとても<ruby>疲<rt>つか</rt></ruby>れました。",
                "romaji": "Kyou wa totemo tsukaremashita.",
                "en": "I got very tired today.",
                "zh": "今天我非常累。",
                "pinyin": "Jīntiān wǒ fēicháng lèi.",
                "bd": [("今日", "today"), ("は", "topic"), ("とても", "very"), ("疲れました", "got tired")],
            },
        ],
    },
    {
        "num": 62,
        "jp": "また〜",
        "romaji": "mata ~",
        "name": "again ~",
        "formula": "また + [verb / phrase]",
        "note": "また = “again.” Use it for repetition, or in friendly farewells like “see you again.”",
        "examples": [
            {
                "jp": "また<ruby>会<rt>あ</rt></ruby>いましょう。",
                "romaji": "Mata aimashou.",
                "en": "Let's meet again.",
                "zh": "我们再见面吧。",
                "pinyin": "Wǒmen zài jiànmiàn ba.",
                "bd": [("また", "again"), ("会いましょう", "let's meet")],
            },
            {
                "jp": "また<ruby>同<rt>おな</rt></ruby>じ<ruby>間違<rt>まちが</rt></ruby>いをしました。",
                "romaji": "Mata onaji machigai o shimashita.",
                "en": "I made the same mistake again.",
                "zh": "我又犯了同样的错误。",
                "pinyin": "Wǒ yòu fàn le tóngyàng de cuòwù.",
                "bd": [("また", "again"), ("同じ", "same"), ("間違い", "mistake"), ("を", "[object]"), ("しました", "made")],
            },
        ],
    },
    {
        "num": 63,
        "jp": "たぶん〜",
        "romaji": "tabun ~",
        "name": "probably ~",
        "formula": "たぶん + [clause]（でしょう）",
        "note": "Express likelihood. たぶん = “probably,” often paired with でしょう or かもしれません.",
        "examples": [
            {
                "jp": "たぶん<ruby>明日<rt>あした</rt></ruby>は<ruby>雨<rt>あめ</rt></ruby>でしょう。",
                "romaji": "Tabun ashita wa ame deshou.",
                "en": "It'll probably rain tomorrow.",
                "zh": "明天大概会下雨。",
                "pinyin": "Míngtiān dàgài huì xià yǔ.",
                "bd": [("たぶん", "probably"), ("明日", "tomorrow"), ("は", "topic"), ("雨", "rain"), ("でしょう", "probably is")],
            },
            {
                "jp": "<ruby>彼<rt>かれ</rt></ruby>はたぶん<ruby>来<rt>き</rt></ruby>ません。",
                "romaji": "Kare wa tabun kimasen.",
                "en": "He probably won't come.",
                "zh": "他大概不来。",
                "pinyin": "Tā dàgài bù lái.",
                "bd": [("彼", "he"), ("は", "topic"), ("たぶん", "probably"), ("来ません", "won't come")],
            },
        ],
    },
    {
        "num": 64,
        "jp": "きっと〜",
        "romaji": "kitto ~",
        "name": "surely / certainly ~",
        "formula": "きっと + [clause]",
        "note": "Express confidence. きっと = “surely / I'm sure,” stronger than たぶん.",
        "examples": [
            {
                "jp": "きっと<ruby>大丈夫<rt>だいじょうぶ</rt></ruby>です。",
                "romaji": "Kitto daijoubu desu.",
                "en": "It'll surely be fine.",
                "zh": "一定没问题。",
                "pinyin": "Yídìng méi wèntí.",
                "bd": [("きっと", "surely"), ("大丈夫", "all right / fine"), ("です", "is")],
            },
            {
                "jp": "<ruby>彼女<rt>かのじょ</rt></ruby>はきっと<ruby>成功<rt>せいこう</rt></ruby>します。",
                "romaji": "Kanojo wa kitto seikou shimasu.",
                "en": "She will surely succeed.",
                "zh": "她一定会成功。",
                "pinyin": "Tā yídìng huì chénggōng.",
                "bd": [("彼女", "she"), ("は", "topic"), ("きっと", "surely"), ("成功します", "will succeed")],
            },
        ],
    },
    {
        "num": 65,
        "jp": "<ruby>念<rt>ねん</rt></ruby>のために〜",
        "romaji": "nen no tame ni ~",
        "name": "just in case ~",
        "formula": "念のために + [action]",
        "note": "Do something as a precaution. 念のために = “just in case / to be safe.”",
        "examples": [
            {
                "jp": "<ruby>念<rt>ねん</rt></ruby>のために<ruby>傘<rt>かさ</rt></ruby>を<ruby>持<rt>も</rt></ruby>っていきます。",
                "romaji": "Nen no tame ni kasa o motte ikimasu.",
                "en": "I'll take an umbrella just in case.",
                "zh": "为了以防万一，我带把伞。",
                "pinyin": "Wèile yǐfáng wànyī, wǒ dài bǎ sǎn.",
                "bd": [("念のために", "just in case"), ("傘", "umbrella"), ("を", "[object]"), ("持っていきます", "take along")],
            },
            {
                "jp": "<ruby>念<rt>ねん</rt></ruby>のためにもう<ruby>一度<rt>いちど</rt></ruby><ruby>確認<rt>かくにん</rt></ruby>します。",
                "romaji": "Nen no tame ni mou ichido kakunin shimasu.",
                "en": "I'll check once more just to be sure.",
                "zh": "为了保险，我再确认一次。",
                "pinyin": "Wèile bǎoxiǎn, wǒ zài quèrèn yí cì.",
                "bd": [("念のために", "to be safe"), ("もう一度", "once more"), ("確認します", "confirm / check")],
            },
        ],
    },
    {
        "num": 66,
        "jp": "〜しないで（ください）",
        "romaji": "~ shinaide (kudasai)",
        "name": "please don't ~",
        "formula": "[verb] ない-form + で + ください",
        "note": "Ask someone not to do something. ない-form + で + ください = “please don't ~.”",
        "examples": [
            {
                "jp": "ここで<ruby>写真<rt>しゃしん</rt></ruby>を<ruby>撮<rt>と</rt></ruby>らないでください。",
                "romaji": "Koko de shashin o toranaide kudasai.",
                "en": "Please don't take photos here.",
                "zh": "请不要在这里拍照。",
                "pinyin": "Qǐng búyào zài zhèlǐ pāizhào.",
                "bd": [("ここ", "here"), ("で", "at"), ("写真", "photo"), ("を", "[object]"), ("撮らないで", "don't take"), ("ください", "please")],
            },
            {
                "jp": "<ruby>心配<rt>しんぱい</rt></ruby>しないでください。",
                "romaji": "Shinpai shinaide kudasai.",
                "en": "Please don't worry.",
                "zh": "请不要担心。",
                "pinyin": "Qǐng búyào dānxīn.",
                "bd": [("心配しないで", "don't worry"), ("ください", "please")],
            },
        ],
    },
    {
        "num": 67,
        "jp": "〜してはいけません",
        "romaji": "~ shitewa ikemasen",
        "name": "must not ~ (forbidden)",
        "formula": "[verb] て-form + はいけません",
        "note": "State a prohibition or rule. て-form + はいけません = “you must not ~.”",
        "examples": [
            {
                "jp": "ここでタバコを<ruby>吸<rt>す</rt></ruby>ってはいけません。",
                "romaji": "Koko de tabako o sutte wa ikemasen.",
                "en": "You must not smoke here.",
                "zh": "这里不可以吸烟。",
                "pinyin": "Zhèlǐ bù kěyǐ xīyān.",
                "bd": [("ここ", "here"), ("で", "at"), ("タバコ", "cigarette"), ("を", "[object]"), ("吸っては", "as for smoking"), ("いけません", "must not")],
            },
            {
                "jp": "<ruby>授業中<rt>じゅぎょうちゅう</rt></ruby>に<ruby>寝<rt>ね</rt></ruby>てはいけません。",
                "romaji": "Jugyou chuu ni nete wa ikemasen.",
                "en": "You must not sleep during class.",
                "zh": "上课时不可以睡觉。",
                "pinyin": "Shàngkè shí bù kěyǐ shuìjiào.",
                "bd": [("授業中", "during class"), ("に", "at"), ("寝ては", "as for sleeping"), ("いけません", "must not")],
            },
        ],
    },
    {
        "num": 68,
        "jp": "〜してみて（ください）",
        "romaji": "~ shitemite (kudasai)",
        "name": "try doing ~",
        "formula": "[verb] て-form + みて（ください）",
        "note": "Suggest trying something out. て-form + みる literally means “do and see,” so + みてください = “try ~ (and see).”",
        "examples": [
            {
                "jp": "この<ruby>服<rt>ふく</rt></ruby>を<ruby>着<rt>き</rt></ruby>てみてください。",
                "romaji": "Kono fuku o kite mite kudasai.",
                "en": "Please try this outfit on.",
                "zh": "请试穿一下这件衣服。",
                "pinyin": "Qǐng shìchuān yíxià zhè jiàn yīfu.",
                "bd": [("この", "this"), ("服", "clothes"), ("を", "[object]"), ("着てみて", "try wearing"), ("ください", "please")],
            },
            {
                "jp": "<ruby>一度<rt>いちど</rt></ruby><ruby>食<rt>た</rt></ruby>べてみてください。",
                "romaji": "Ichido tabete mite kudasai.",
                "en": "Try eating it once.",
                "zh": "请尝一下。",
                "pinyin": "Qǐng cháng yíxià.",
                "bd": [("一度", "once"), ("食べてみて", "try eating"), ("ください", "please")],
            },
        ],
    },
    {
        "num": 69,
        "jp": "〜、お<ruby>願<rt>ねが</rt></ruby>いします",
        "romaji": "~, onegai shimasu",
        "name": "~, please / I'd like ~",
        "formula": "[noun] を + お願いします",
        "note": "Politely request a thing or service. Noun + をお願いします — common when ordering or asking for help.",
        "examples": [
            {
                "jp": "コーヒーをお<ruby>願<rt>ねが</rt></ruby>いします。",
                "romaji": "Koohii o onegai shimasu.",
                "en": "Coffee, please.",
                "zh": "请给我一杯咖啡。",
                "pinyin": "Qǐng gěi wǒ yì bēi kāfēi.",
                "bd": [("コーヒー", "coffee"), ("を", "[object]"), ("お願いします", "please (I request)")],
            },
            {
                "jp": "<ruby>会計<rt>かいけい</rt></ruby>をお<ruby>願<rt>ねが</rt></ruby>いします。",
                "romaji": "Kaikei o onegai shimasu.",
                "en": "The check, please.",
                "zh": "请结账。",
                "pinyin": "Qǐng jiézhàng.",
                "bd": [("会計", "bill / check"), ("を", "[object]"), ("お願いします", "please (I request)")],
            },
        ],
    },
    {
        "num": 70,
        "jp": "〜をください",
        "romaji": "~ wo kudasai",
        "name": "please give me ~",
        "formula": "[noun] を + ください",
        "note": "Ask for a thing directly. Noun + をください = “please give me ~.” Add a counter for quantity.",
        "examples": [
            {
                "jp": "<ruby>水<rt>みず</rt></ruby>を<ruby>一杯<rt>いっぱい</rt></ruby>ください。",
                "romaji": "Mizu o ippai kudasai.",
                "en": "Please give me a glass of water.",
                "zh": "请给我一杯水。",
                "pinyin": "Qǐng gěi wǒ yì bēi shuǐ.",
                "bd": [("水", "water"), ("を", "[object]"), ("一杯", "one glass"), ("ください", "please give me")],
            },
            {
                "jp": "これをください。",
                "romaji": "Kore o kudasai.",
                "en": "I'll take this one.",
                "zh": "请给我这个。",
                "pinyin": "Qǐng gěi wǒ zhège.",
                "bd": [("これ", "this"), ("を", "[object]"), ("ください", "please give me")],
            },
        ],
    },
    {
        "num": 71,
        "jp": "〜してください",
        "romaji": "~ shite kudasai",
        "name": "please do ~",
        "formula": "[verb] て-form + ください",
        "note": "The standard polite request. Take the て-form of the verb and add ください.",
        "examples": [
            {
                "jp": "もう<ruby>一度<rt>いちど</rt></ruby><ruby>言<rt>い</rt></ruby>ってください。",
                "romaji": "Mou ichido itte kudasai.",
                "en": "Please say it once more.",
                "zh": "请再说一遍。",
                "pinyin": "Qǐng zài shuō yí biàn.",
                "bd": [("もう一度", "once more"), ("言って", "say"), ("ください", "please")],
            },
            {
                "jp": "ゆっくり<ruby>話<rt>はな</rt></ruby>してください。",
                "romaji": "Yukkuri hanashite kudasai.",
                "en": "Please speak slowly.",
                "zh": "请说慢一点。",
                "pinyin": "Qǐng shuō màn yìdiǎn.",
                "bd": [("ゆっくり", "slowly"), ("話して", "speak"), ("ください", "please")],
            },
        ],
    },
    {
        "num": 72,
        "jp": "〜していただけませんか",
        "romaji": "~ shite itadakemasen ka",
        "name": "could you please ~? (very polite)",
        "formula": "[verb] て-form + いただけませんか",
        "note": "A very polite, humble request. て-form + いただけませんか is softer and more deferential than ください.",
        "examples": [
            {
                "jp": "<ruby>写真<rt>しゃしん</rt></ruby>を<ruby>撮<rt>と</rt></ruby>っていただけませんか。",
                "romaji": "Shashin o totte itadakemasen ka.",
                "en": "Could you take a photo for me?",
                "zh": "能帮我拍张照吗？",
                "pinyin": "Néng bāng wǒ pāi zhāng zhào ma?",
                "bd": [("写真", "photo"), ("を", "[object]"), ("撮って", "take"), ("いただけませんか", "could you please?")],
            },
            {
                "jp": "もう<ruby>少<rt>すこ</rt></ruby>し<ruby>待<rt>ま</rt></ruby>っていただけませんか。",
                "romaji": "Mou sukoshi matte itadakemasen ka.",
                "en": "Could you wait a little longer?",
                "zh": "能再等一会儿吗？",
                "pinyin": "Néng zài děng yíhuìr ma?",
                "bd": [("もう少し", "a little more"), ("待って", "wait"), ("いただけませんか", "could you please?")],
            },
        ],
    },
]
